apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-efshsrpt
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-efshsrpt:2caaa1b2b1347e069a6cce5b8e4bae63c6d83f56@sha256:c163401e80ba50e425abe6247ec9b93b57419602d72a2580bac14ca30d3c24a3
        name: container-image  
